["setup.cfg".isort]
# these values should be placed inside `setup.cfg` in your repo:
lexicographical = true
force_sort_within_sections = true
force_single_line = true
src_paths = src,tests
single_line_exclusions = typing
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
